{% set name = "qpsolvers" %}
{% set version = "4.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qpsolvers-{{ version }}.tar.gz
  sha256: c7a4b297b56a6b44270b9bc0c57122a211cc61aaae6bcd1e9fa49ff9340ce614

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - flit-core
  run:
    - python >=3.5
    - quadprog >=0.1.8
    - ecos
    - cvxopt
    - osqp
    - qpoases
    - proxsuite
    - numpy
    - scipy
    - scs
    - daqp

test:
  imports:
    - qpsolvers
  commands:
    - pip check
    - python -c "import qpsolvers; print(qpsolvers.available_solvers)"
  requires:
    - pip

about:
  home: https://github.com/stephane-caron/qpsolvers
  summary: Quadratic Programming solvers for Python with a unified API
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
