{% set name = "qpsolvers" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qpsolvers-{{ version }}.tar.gz
  sha256: 3606aa9b76d62ce8576da47c1a797ca1e0937e5ebda3c69aed3926a43f50a664

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - flit-core
  run:
    - python >=3.5
    - quadprog >=0.1.8
    - ecos
    - cvxopt
    - osqp

test:
  imports:
    - qpsolvers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stephane-caron/qpsolvers
  summary: Quadratic Programming solvers for Python with a unified API
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
