{% set name = "qpsolvers" %}
{% set version = "4.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qpsolvers-{{ version }}.tar.gz
  sha256: 93c2fb505738b110f4c130d8d9b9a351bef6e8e10c5fc69650c16bcfded1c676

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - flit-core
  run:
    - python >=3.5
    - numpy
    - scipy

test:
  imports:
    - qpsolvers
  commands:
    - pip check
    - python -c "import qpsolvers; print(qpsolvers.available_solvers)"
  requires:
    - pip

about:
  home: https://github.com/stephane-caron/qpsolvers
  summary: Quadratic Programming solvers for Python with a unified API
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
