{% set name = "qpsolvers" %}
{% set version = "4.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qpsolvers-{{ version }}.tar.gz
  sha256: ab26fb2ce240ff08ad15c04d57056dc8a77c853ffce29c30bf9333b92ccc726e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core
  run:
    - python >={{ python_min }}
    - osqp
    - proxsuite
    - numpy
    - scipy
    - scs
    - daqp
    # While qpsolvers is distributed under the LGPL-3.0 license, the following
    # solvers are distributed under GPL-2.0 or GPL-3.0 licenses. If you install
    # them qpsolvers will detect and work with them, but the GPL will then
    # affect the license under which you can distribute your software.
    # See also: https://github.com/conda-forge/qpsolvers-feedstock/issues/51
    # - cvxopt
    # - ecos
    # - quadprog >=0.1.8

test:
  imports:
    - qpsolvers
  commands:
    - pip check
    - python -c "import qpsolvers; print(qpsolvers.available_solvers)"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/stephane-caron/qpsolvers
  summary: Quadratic Programming solvers for Python with a unified API
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
