{% set name = "qpsolvers" %}
{% set version = "4.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qpsolvers-{{ version }}.tar.gz
  sha256: d3901c515cc1974b2e28984d4b6dc30cd320366c233394993b547dbe1f600e7e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core
  run:
    - python >={{ python_min }}
    - quadprog >=0.1.8
    - ecos
    - cvxopt
    - osqp
    - proxsuite
    - numpy
    - scipy
    - scs
    - daqp

test:
  imports:
    - qpsolvers
  commands:
    - pip check
    - python -c "import qpsolvers; print(qpsolvers.available_solvers)"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/stephane-caron/qpsolvers
  summary: Quadratic Programming solvers for Python with a unified API
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
